config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get '/search', :to => 'reservations#home'

  get '/flights/new', :to => 'flights#home'

  get 'session/new'


  resources :reservations
  resources :flights
  resources :airplanes
  resources :users

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

  get '/planes/airbus' => 'airplanes#airbus300', :as => 'airbus'
  get '/planes/privatejet' => 'airplanes#privateJet', :as => 'privatejet'
  get '/planes/boeing747' => 'airplanes#boeing747', :as => 'boeing747'


end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id            :integer          not null, primary key
#  flight_number :text
#  origin        :text
#  destination   :text
#  date          :datetime
#  plane         :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Flight < ActiveRecord::Base
  has_many :reservations
  belongs_to :airplane
  has_many :users, :through => :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]


  def index
    @flights = Flight.all
  end


  def show
    @flight = Flight.find params[:id]
  end


  def new
    @flight = Flight.new
  end


  def edit
    @flight = Flight.find params[:id]
  end


  def create
    @flight = Flight.create flight_params


    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_flight
      @flight = Flight.find(params[:id])
    end


    def flight_params
      params.require(:flight).permit(:flight_number, :origin, :destination, :date, :plane, :airplane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_number %><br>
    <%= f.text_area :flight_number %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_area :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_area :destination %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :airplane_id %><br>
    <%= f.select :airplane_id, Airplane.all.map { |a| [a.name, a.id]}, :include_blank => true %>
    <!-- <%= f.collection_select(:airplane_id, Airplane.all, :id, :name) %> -->

    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/home.html.erb
<div id="main">
  Burning Airlines
</div>

<script id="appViewTemplate" type="html/template">
  <h1>Create A Flight</h1>

  <div id="flightNameForm">
  </div>

 <ul id="flights">
 </ul>
</script>

<script id="flightInputViewTemplate" type="html/template">
<div id="flightNumber">
<input class="flightNumber" type="text" name="flightNumberForm" placeholder="flight number" style="text-transform:uppercase"></input>
</div>
<br/>
<div id="flightOrigin">
<input class="flightOrigin" type="text" name="flightOriginForm" placeholder="flight origin" style="text-transform:uppercase"></input>
</div>
<br/>
<div id="flightDestination">
<input class="flightDestination" type="text" name="flightDestinationForm" placeholder="flight destination" style="text-transform:uppercase"></input>
</div>
<br/>
<div id="flightDate">
<input class="flightDate" type="datetime-local" name="flightDateForm" placeholder="flight date"></input>
</div>
<br/>
<div id="flightPlane">
<select name="" id="">
<%= options_for_select Airplane.all.map { |a| [a.name, a.id] }, :include_blank => true %>
</select>
</div>
<br/>
<button type="submit" value="Submit">Submit</button>
<br/>
</script>


<!-- $("select").val(); will get the id
$("select option:selected").text(); will get the selected text -->

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<table>
  <thead>
    <tr>
      <th>Flight Number</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Plane</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_number %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.date %></td>
        <td><%= flight.plane %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<div id="main">
  Burning Airlines
</div>


<script id="appViewTemplate" type="html/template">
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight number:</strong>
  <%= @flight.flight_number %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>Plane:</strong>
  <%= @flight.plane %>
</p>

  <h1>Seats</h1>

  <div id="seatBoard">
  </div>

  <ul id="selectedSeat">
  </ul>
</script>


<script id="flightSeatInputViewTemplate" type="html/template">

<ul class="row1">
  <p></p>
  <li class="seat seat1" data-row='0' data-column='A'></li>
  <li class="seat seat2" data-row='0' data-column='B'></li>
  <li class="seat seat3" data-row='0' data-column='C'></li>
  <li class="seat seat4" data-row='0' data-column='D'></li>

</ul>
<ul class="row2">
  <li class="seat seat5" data-row='1' data-column='A'></li>
  <li class="seat seat6" data-row='1' data-column='B'></li>
  <li class="seat seat7" data-row='1' data-column='C'></li>
  <li class="seat seat8" data-row='1' data-column='D'></li>

</ul>

</script>


<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>