config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get '/search', :to => 'reservations#home'

  get '/flights/new', :to => 'flights#home'

  get 'session/new'


  resources :reservations
  resources :flights
  resources :airplanes
  resources :users

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

  get '/planes/airbus' => 'airplanes#airbus300', :as => 'airbus'
  get '/planes/privatejet' => 'airplanes#privateJet', :as => 'privatejet'
  get '/planes/boeing747' => 'airplanes#boeing747', :as => 'boeing747'


end

app/models/airplane.rb
# == Schema Information
#
# Table name: airplanes
#
#  id         :integer          not null, primary key
#  row        :integer
#  column     :text
#  name       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Airplane < ActiveRecord::Base
  has_many :flights
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]


  def index
    @airplanes = Airplane.all
  end


  def show
    @airplane = Airplane.find params[:id]
  end


  def new
    @airplane = Airplane.new
    @airplanes = Airplane.all
  end


  def edit
    @airplane = Airplane.find params[:id]
  end


  def create
    @airplane = Airplane.create airplane_params
    @airplanes = Airplane.all

    redirect_to "/airplane/#{airplane.id}"

  end


  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def airbus300
    # @airplane =
  end

  def boeing747

  end


  def privateJet

  end

  private

    def set_airplane
      @airplane = Airplane.find(params[:id])
    end


    def airplane_params
      params.require(:airplane).permit(:row, :column, :name)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/Airbus300.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AirBus</title>
</head>
<body>
<h2>This is the Airbus 300</h2>
  <div class="Airbus">
    <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/5/59/Airbus_A300-600ST_Airbus_Industries_(AIB)_Beluga_2_F-GSTB_-_MSN_751_(9738915761).jpg", class: 'main' %>
  </div>

<p>Standard Airbus 300 Seating Chart </p>

  <ul class="column1">
    <p></p>
    <li class="seat" data-row='0' data-column='A'>1A</li>
    <li class="seat" data-row='0' data-column='B'>1B</li>
    <li class="seat" data-row='0' data-column='C'>1C</li>
    <li class="seat" data-row='0' data-column='D'>1D</li>

  </ul>
  <ul class="column2">
    <li class="seat" data-row='1' data-column='A'>2A</li>
    <li class="seat" data-row='1' data-column='B'>2B</li>
    <li class="seat" data-row='1' data-column='C'>2C</li>
    <li class="seat" data-row='1' data-column='D'>2D</li>

  </ul>
  <ul class="column3">
    <li class="seat" data-row='2' data-column='A'>3A</li>
    <li class="seat" data-row='2' data-column='B'>3B</li>
    <li class="seat" data-row='2' data-column='C'>3C</li>
    <li class="seat" data-row='2' data-column='D'>3D</li>

  </ul>
  <ul class="column3">
    <li class="seat" data-row='3' data-column='A'>4A</li>
    <li class="seat" data-row='3' data-column='B'>4B</li>
    <li class="seat" data-row='3' data-column='C'>4C</li>
    <li class="seat" data-row='3' data-column='D'>4D</li>

  </ul>
  <ul class="column4">
    <li class="seat" data-row='4' data-column='A'>5A</li>
    <li class="seat" data-row='4' data-column='B'>5B</li>
    <li class="seat" data-row='4' data-column='C'>5C</li>
    <li class="seat" data-row='4' data-column='D'>5D</li>

  </ul>
  <ul class="column5">
    <li class="seat" data-row='5' data-column='A'>6A</li>
    <li class="seat" data-row='5' data-column='B'>6B</li>
    <li class="seat" data-row='5' data-column='C'>6C</li>
    <li class="seat" data-row='5' data-column='D'>6D</li>

  </ul>
  <ul class="column6">
    <li class="seat" data-row='6' data-column='A'>7A</li>
    <li class="seat" data-row='6' data-column='B'>7B</li>
    <li class="seat" data-row='6' data-column='C'>7C</li>
    <li class="seat" data-row='6' data-column='D'>7D</li>

  </ul>
  <ul class="column7">
    <li class="seat" data-row='7' data-column='A'>8A</li>
    <li class="seat" data-row='7' data-column='B'>8B</li>
    <li class="seat" data-row='7' data-column='C'>8C</li>
    <li class="seat" data-row='7' data-column='D'>8D</li>

  </ul>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="airplanes.js"></script>
</body>
</html>
<!--

app/views/airplanes/Boeing747.html.erb
<h2>This is the Boeing 747</h2>

<div class="Boeing">
  <%= image_tag "http://www.britishairways.com/assets/images/information/about-ba/fleet-facts/boeing-747-400/photo-gallery/750x500-boeing747-400-2.jpg", class: 'main' %>
</div>
<p>Standard Boeing 747 Seating Chart </p>


  <ul class="column1">
    <p></p>
    <li class="seat" data-row='0' data-column='A'>1A</li>
    <li class="seat" data-row='0' data-column='B'>1B</li>
    <li class="seat" data-row='0' data-column='C'>1C</li>
    <li class="seat" data-row='0' data-column='D'>1D</li>
    <li class="seat" data-row='0' data-column='E'>1E</li>
    <li class="seat" data-row='0' data-column='F'>1F</li>
  </ul>
  <ul class="column2">
    <li class="seat" data-row='1' data-column='A'>2A</li>
    <li class="seat" data-row='1' data-column='B'>2B</li>
    <li class="seat" data-row='1' data-column='C'>2C</li>
    <li class="seat" data-row='1' data-column='D'>2D</li>
    <li class="seat" data-row='1' data-column='E'>2E</li>
    <li class="seat" data-row='1' data-column='F'>2F</li>
  </ul>
  <ul class="column3">
    <li class="seat" data-row='2' data-column='A'>3A</li>
    <li class="seat" data-row='2' data-column='B'>3B</li>
    <li class="seat" data-row='2' data-column='C'>3C</li>
    <li class="seat" data-row='2' data-column='D'>3D</li>
    <li class="seat" data-row='2' data-column='E'>3E</li>
    <li class="seat" data-row='2' data-column='F'>3F</li>
  </ul>
  <ul class="column3">
    <li class="seat" data-row='3' data-column='A'>4A</li>
    <li class="seat" data-row='3' data-column='B'>4B</li>
    <li class="seat" data-row='3' data-column='C'>4C</li>
    <li class="seat" data-row='3' data-column='D'>4D</li>
    <li class="seat" data-row='3' data-column='E'>4E</li>
    <li class="seat" data-row='3' data-column='F'>4F</li>
  </ul>
  <ul class="column4">
    <li class="seat" data-row='4' data-column='A'>5A</li>
    <li class="seat" data-row='4' data-column='B'>5B</li>
    <li class="seat" data-row='4' data-column='C'>5C</li>
    <li class="seat" data-row='4' data-column='D'>5D</li>
    <li class="seat" data-row='4' data-column='E'>5E</li>
    <li class="seat" data-row='4' data-column='F'>5F</li>
  </ul>
  <ul class="column5">
    <li class="seat" data-row='5' data-column='A'>6A</li>
    <li class="seat" data-row='5' data-column='B'>6B</li>
    <li class="seat" data-row='5' data-column='C'>6C</li>
    <li class="seat" data-row='5' data-column='D'>6D</li>
    <li class="seat" data-row='5' data-column='E'>6E</li>
    <li class="seat" data-row='5' data-column='F'>6F</li>
  </ul>
  <ul class="column6">
    <li class="seat" data-row='6' data-column='A'>7A</li>
    <li class="seat" data-row='6' data-column='B'>7B</li>
    <li class="seat" data-row='6' data-column='C'>7C</li>
    <li class="seat" data-row='6' data-column='D'>7D</li>
    <li class="seat" data-row='6' data-column='E'>7E</li>
    <li class="seat" data-row='6' data-column='F'>7F</li>
  </ul>
  <ul class="column7">
    <li class="seat" data-row='7' data-column='A'>8A</li>
    <li class="seat" data-row='7' data-column='B'>8B</li>
    <li class="seat" data-row='7' data-column='C'>8C</li>
    <li class="seat" data-row='7' data-column='D'>8D</li>
    <li class="seat" data-row='7' data-column='E'>8E</li>
    <li class="seat" data-row='7' data-column='F'>8F</li>
  </ul>
  <ul class="column8">
    <li class="seat" data-row='8' data-column='A'>9A</li>
    <li class="seat" data-row='8' data-column='B'>9B</li>
    <li class="seat" data-row='8' data-column='C'>9C</li>
    <li class="seat" data-row='8' data-column='D'>9D</li>
    <li class="seat" data-row='8' data-column='E'>9E</li>
    <li class="seat" data-row='8' data-column='F'>9F</li>
  </ul>
  <ul class="column9">
    <li class="seat" data-row='9' data-column='A'>9A</li>
    <li class="seat" data-row='9' data-column='B'>9B</li>
    <li class="seat" data-row='9' data-column='C'>9C</li>
    <li class="seat" data-row='9' data-column='D'>9D</li>
    <li class="seat" data-row='9' data-column='E'>9E</li>
    <li class="seat" data-row='9' data-column='F'>9F</li>
  </ul>
  <ul class="column10">
    <li class="seat" data-row='10' data-row='A'>10A</li>
    <li class="seat" data-row='10' data-row='B'>10B</li>
    <li class="seat" data-row='10' data-row='C'>10C</li>
    <li class="seat" data-row='10' data-row='D'>10D</li>
    <li class="seat" data-row='10' data-row='E'>10E</li>
    <li class="seat" data-row='10' data-row='F'>10F</li>
  </ul>

</div>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="airplanes.js"></script>
</body>
</html>

app/views/airplanes/PrivateJet.html.erb
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Private Jet</title>
</head> -->
<body>
  <h2>Ooooh you fancy. This is the Private Jet</h2>

  <div class="PrivatePlane">
    <%= image_tag "http://jetlux.com/images/Private-Jet-Dental-Holidays.png", class: 'main' %>
  </div>


  <ul class="column1">
    <p></p>
    <li class="seat" data-row='0' data-column='A'>1A</li>
    <li class="seat" data-row='0' data-column='B'>1B</li>

  </ul>
  <ul class="column2">
    <li class="seat" data-row='1' data-column='A'>2A</li>
    <li class="seat" data-row='1' data-column='B'>2B</li>

  </ul>
  <ul class="column3">
    <li class="seat" data-row='2' data-column='A'>3A</li>
    <li class="seat" data-row='2' data-column='B'>3B</li>

  </ul>
  <ul class="column3">
    <li class="seat" data-row='3' data-column='A'>4A</li>
    <li class="seat" data-row='3' data-column='B'>4B</li>
  </ul>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="airplanes.js"></script>
</body>
</html>

app/views/airplanes/_form.html.erb
<%= link_to airbus_path do %>
  <div class="Airbus">
    <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/5/59/Airbus_A300-600ST_Airbus_Industries_(AIB)_Beluga_2_F-GSTB_-_MSN_751_(9738915761).jpg", class: 'thumbnail' %>
  </div>
<%end%>
<%= link_to privatejet_path do %>
  <div class="PrivatePlane">
    <%= image_tag "http://jetlux.com/images/Private-Jet-Dental-Holidays.png", class: 'thumbnail' %>
  </div>
<% end %>
<%= link_to boeing747_path do %>
  <div class="Boeing">
    <%= image_tag "http://www.britishairways.com/assets/images/information/about-ba/fleet-facts/boeing-747-400/photo-gallery/750x500-boeing747-400-2.jpg", class: 'thumbnail'%>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form' %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Airplanes</h1>

<table>
  <thead>
    <tr>
      <th>Row</th>
      <th>Column</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.row %></td>
        <td><%= airplane.column %></td>
        <td><%= airplane.name %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

app/views/airplanes/new.html.erb
<link href="airplanes.scss" rel="stylesheet">

<h1>Pick an Airplane</h1>

<%= render 'form' %>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Row:</strong>
  <%= @airplane.row %>
</p>

<p>
  <strong>Column:</strong>
  <%= @airplane.column %>
</p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>



<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>