config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get '/search', :to => 'reservations#home'

  get '/flights/new', :to => 'flights#home'

  get 'session/new'


  resources :reservations
  resources :flights
  resources :airplanes
  resources :users

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

  get '/planes/airbus' => 'airplanes#airbus300', :as => 'airbus'
  get '/planes/privatejet' => 'airplanes#privateJet', :as => 'privatejet'
  get '/planes/boeing747' => 'airplanes#boeing747', :as => 'boeing747'


end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :flight
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.all
  end

  def home
    @users = User.all
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end


  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.fetch(:reservation, {}).permit(:user_id, :flight_id, :seatID)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, User.all.map{ |u| [ u.name, u.id ] }, :include_blank => true %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :flight_id %><br>
    <%= f.select :flight_id, Flight.all.map{ |f| [ f.flight_number, f.id ] }, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :seatID %><br>
    <%= f.text_area :seatID %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/home.html.erb
<div id="main">
  Burning Airlines
</div>
<p id="user_name">
<%= @current_user.name %>
</p>
<p id="user_id">
<%= @current_user.id %>
</p>

<script id="appViewTemplate" type="html/template">
  <h1>Search Flights</h1>

  <div id="searchWord">
  </div>

  <ul id="results">
  </ul>
</script>

<script id="searchInputViewTemplate" type="html/template">

<div id="searchOrigin">
<input class="searchOrigin" type="text" name="searchOriginForm" placeholder="Origin" style="text-transform:uppercase"></input>
</div>
<br/>
<div id="searchDestination">
<input class="searchDestination" type="text" name="searchDestinationForm" placeholder="Destination" style="text-transform:uppercase"></input>
</div>
<br/>

<button type="submit" value="Submit">Submit</button>


</script>

  <script id="flightTemplate" type="html/template">

    <h1>Seats</h1>

    <div class="flightInfo"
    <strong>Flight Number: </strong><span id="flight_number"></span>
    <br/>
    From: <span id="origin"></span>
    <span> / </span>
    To: <span id="destination"></span>
    <br/>
    Date: <span id="date"></span>
    <br/>
    Plane: <span id="plane">
    </div>


    <div id="seatBoard">
        <ul class="row1">
          <li class="seat seat1" data-row='0' data-column='A'></li>
          <li class="seat seat2" data-row='0' data-column='B'></li>
          <li class="seat seat3" data-row='0' data-column='C'></li>
          <li class="seat seat4" data-row='0' data-column='D'></li>
        </ul>
        <ul class="row2">
          <li class="seat seat5" data-row='1' data-column='A'></li>
          <li class="seat seat6" data-row='1' data-column='B'></li>
          <li class="seat seat7" data-row='1' data-column='C'></li>
          <li class="seat seat8" data-row='1' data-column='D'></li>

        </ul>
    </div>

    <ul id="selectedSeat"></ul>
    <button id="save">Save</button>


  </script>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.flight_id %></td>
        <td><%= reservation.seatID %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>